#!/bin/bash

ENJIMA_DIR=$HOME/src/enjima
INCLUDE_TARGET_DIR="./include"
API_DIR_SUFFIX="enjima/api"
CORE_DIR_SUFFIX="enjima/core"
MEM_DIR_SUFFIX="enjima/memory"
QUEUEING_DIR_SUFFIX="enjima/queueing"
METRICS_DIR_SUFFIX="enjima/metrics"
OPS_DIR_SUFFIX="enjima/operators"
RUNTIME_DIR_SUFFIX="enjima/runtime"
SCHEDULING_DIR_SUFFIX="enjima/runtime/scheduling"
COMMON_DIR_SUFFIX="enjima/common"

TARGET_LIB_DIR="./lib"
SRC_LIB_DIR_DBG="cmake-build-debug"
SRC_LIB_DIR_REL_WITH_DBG="cmake-build-relwithdebinfo"
SRC_LIB_DIR_REL="cmake-build-release"
LIB_NAME_DBG="libEnjimaDebug.a"
LIB_NAME_REL_WITH_DBG="libEnjimaRelWithDebInfo.a"
LIB_NAME_REL="libEnjimaRelease.a"

USE_REL_WITH_DBG="true"
COPY_COMMAND='cp'

echo "Copying header files and template defintion files..."

echo "Copying all files from $COMMON_DIR_SUFFIX directory"
$COPY_COMMAND -r $ENJIMA_DIR/$COMMON_DIR_SUFFIX/* $INCLUDE_TARGET_DIR/$COMMON_DIR_SUFFIX/

echo "Copying all files from enjima/api directory"
$COPY_COMMAND -r $ENJIMA_DIR/$API_DIR_SUFFIX/* $INCLUDE_TARGET_DIR/$API_DIR_SUFFIX/

echo "Copying relevant .h and .tpp files in $CORE_DIR_SUFFIX ..."
$COPY_COMMAND $ENJIMA_DIR/$CORE_DIR_SUFFIX/CoreInternals.fwd.h $INCLUDE_TARGET_DIR/$CORE_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$CORE_DIR_SUFFIX/CoreTypeAliases.h $INCLUDE_TARGET_DIR/$CORE_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$CORE_DIR_SUFFIX/InstanceID.h $INCLUDE_TARGET_DIR/$CORE_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$CORE_DIR_SUFFIX/InstanceID.tpp $INCLUDE_TARGET_DIR/$CORE_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$CORE_DIR_SUFFIX/OutputCollector.h $INCLUDE_TARGET_DIR/$CORE_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$CORE_DIR_SUFFIX/OutputCollector.tpp $INCLUDE_TARGET_DIR/$CORE_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$CORE_DIR_SUFFIX/Record.h $INCLUDE_TARGET_DIR/$CORE_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$CORE_DIR_SUFFIX/Record.tpp $INCLUDE_TARGET_DIR/$CORE_DIR_SUFFIX/

echo "Copying relevant .h and .tpp files in $MEM_DIR_SUFFIX ..."
$COPY_COMMAND $ENJIMA_DIR/$MEM_DIR_SUFFIX/MemoryAllocator.h $INCLUDE_TARGET_DIR/$MEM_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$MEM_DIR_SUFFIX/MemoryBlock.h $INCLUDE_TARGET_DIR/$MEM_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$MEM_DIR_SUFFIX/MemoryBlock.tpp $INCLUDE_TARGET_DIR/$MEM_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$MEM_DIR_SUFFIX/MemoryChunk.h $INCLUDE_TARGET_DIR/$MEM_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$MEM_DIR_SUFFIX/MemoryInternals.fwd.h $INCLUDE_TARGET_DIR/$MEM_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$MEM_DIR_SUFFIX/MemoryManager.fwd.h $INCLUDE_TARGET_DIR/$MEM_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$MEM_DIR_SUFFIX/MemoryManager.h $INCLUDE_TARGET_DIR/$MEM_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$MEM_DIR_SUFFIX/MemoryManager.tpp $INCLUDE_TARGET_DIR/$MEM_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$MEM_DIR_SUFFIX/MemoryAllocationCoordinator.h $INCLUDE_TARGET_DIR/$MEM_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$MEM_DIR_SUFFIX/MemoryTypeAliases.h $INCLUDE_TARGET_DIR/$MEM_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$MEM_DIR_SUFFIX/MemoryUtil.h $INCLUDE_TARGET_DIR/$MEM_DIR_SUFFIX/

echo "Copying relevant .h and .tpp files in $METRICS_DIR_SUFFIX ..."
$COPY_COMMAND $ENJIMA_DIR/$METRICS_DIR_SUFFIX/*.h $INCLUDE_TARGET_DIR/$METRICS_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$METRICS_DIR_SUFFIX/*.tpp $INCLUDE_TARGET_DIR/$METRICS_DIR_SUFFIX/

echo "Copying relevant .h and .tpp files in $METRICS_DIR_SUFFIX/types ..."
$COPY_COMMAND $ENJIMA_DIR/$METRICS_DIR_SUFFIX/types/*.h $INCLUDE_TARGET_DIR/$METRICS_DIR_SUFFIX/types/
$COPY_COMMAND $ENJIMA_DIR/$METRICS_DIR_SUFFIX/types/*.tpp $INCLUDE_TARGET_DIR/$METRICS_DIR_SUFFIX/types/

echo "Copying relevant .h and .tpp files in $OPS_DIR_SUFFIX ..."
$COPY_COMMAND $ENJIMA_DIR/$OPS_DIR_SUFFIX/*.h $INCLUDE_TARGET_DIR/$OPS_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$OPS_DIR_SUFFIX/*.tpp $INCLUDE_TARGET_DIR/$OPS_DIR_SUFFIX/

echo "Copying relevant .h and .tpp files in $QUEUEING_DIR_SUFFIX ..."
$COPY_COMMAND $ENJIMA_DIR/$QUEUEING_DIR_SUFFIX/*.h $INCLUDE_TARGET_DIR/$QUEUEING_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$QUEUEING_DIR_SUFFIX/*.tpp $INCLUDE_TARGET_DIR/$QUEUEING_DIR_SUFFIX/

echo "Copying relevant .h and .tpp files in $RUNTIME_DIR_SUFFIX ..."
$COPY_COMMAND $ENJIMA_DIR/$RUNTIME_DIR_SUFFIX/ExecutionEngine.h $INCLUDE_TARGET_DIR/$RUNTIME_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$RUNTIME_DIR_SUFFIX/ExecutionEngine.fwd.h $INCLUDE_TARGET_DIR/$RUNTIME_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$RUNTIME_DIR_SUFFIX/RuntimeInternals.fwd.h $INCLUDE_TARGET_DIR/$RUNTIME_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$RUNTIME_DIR_SUFFIX/RuntimeUtil.h $INCLUDE_TARGET_DIR/$RUNTIME_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$RUNTIME_DIR_SUFFIX/RuntimeUtil.tpp $INCLUDE_TARGET_DIR/$RUNTIME_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$RUNTIME_DIR_SUFFIX/RuntimeTypes.h $INCLUDE_TARGET_DIR/$RUNTIME_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$RUNTIME_DIR_SUFFIX/StreamingJob.h $INCLUDE_TARGET_DIR/$RUNTIME_DIR_SUFFIX/
$COPY_COMMAND $ENJIMA_DIR/$RUNTIME_DIR_SUFFIX/StreamingTask.h $INCLUDE_TARGET_DIR/$RUNTIME_DIR_SUFFIX/

echo "Copying relevant .h and .tpp files in $SCHEDULING_DIR_SUFFIX ..."
$COPY_COMMAND $ENJIMA_DIR/$SCHEDULING_DIR_SUFFIX/SchedulingTypes.h $INCLUDE_TARGET_DIR/$SCHEDULING_DIR_SUFFIX/

echo "Copying static library $LIB_NAME_DBG from $SRC_LIB_DIR_DBG to $TARGET_LIB_DIR ..."
$COPY_COMMAND $ENJIMA_DIR/$SRC_LIB_DIR_DBG/$LIB_NAME_DBG $TARGET_LIB_DIR/

if [[ $USE_REL_WITH_DBG == "true" ]]; then
	echo "Copying static library $LIB_NAME_REL_WITH_DBG from $SRC_LIB_DIR_REL_WITH_DBG to $TARGET_LIB_DIR ..."
	$COPY_COMMAND $ENJIMA_DIR/$SRC_LIB_DIR_REL_WITH_DBG/$LIB_NAME_REL_WITH_DBG $TARGET_LIB_DIR/
fi

echo "Copying static library $LIB_NAME_REL from $SRC_LIB_DIR_REL to $TARGET_LIB_DIR ..."
$COPY_COMMAND $ENJIMA_DIR/$SRC_LIB_DIR_REL/$LIB_NAME_REL $TARGET_LIB_DIR/

echo "Done."
